server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: ims
    password: ims12!@
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://192.168.0.17:3309/ims?serverTimezone=UTC&allowPublicKeyRetrieval=true

